spring:
  application:
    name: blog-service

  sleuth:
    enabled: true
  zipkin:
    enabled: false

  cloud:
    config:
      uri: http://localhost:8888

  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 9090