server:
  port: 9091

spring:
  application:
    name: blogwriter-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service
  config:
    import: 'optional:configserver:'

  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
    base-url: http://localhost:9411

