spring:
  application:
    name: api-gateway

  sleuth:
    enabled: true
    sampler:
      probability: 1.0
    baggage:
      remote-fields: app-session-id
      correlation-fields: app-session-id
      correlation-enabled: true
      tag-fields: app-session-id
  zipkin:
    enabled: true
    base-url: http://localhost:9411

server:
  port: 8080

#spring:
#  application:
#    name: api-gateway-service
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        - id: blog-service
#          predicates:
#            - Path=blogs/**
#            - Method=GET
#          uri: http://localhost:9090
#          filters:
#            - PrefixPath=/mypath

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always